### ISSUE TITLE
потенциальная ошибка

### ISSUE THREAD

**Issue by NikiIva** [FedorSergeev/keepup#26]
https://github.com/FedorSergeev/keepup/blob/23bc2e5ac9b149d2a4fc84b38548af4c182a73cc/core/src/main/java/io/keepup/cms/core/commons/ApplicationConfig.java#L84-L107

Вот тут траи одинаково выглядят и блоки кетч одни и те же

**Comment by FedorSergeev** [comment]
Можно выделить их в отдельные функции, чтобы статические директории создавались в одном блоке кода, но с разными параметрами и разным логгированием ошибок. Взято в работу
